db:
  image: mysql
  volumes:
    - ./mysql/runtime:/var/lib/mysql
  env_file:
    - ./.env
app:
  image: timezstyle/wordpress
  links:
    - db:mysql
  volumes:
    - ./data:/var/www/html/wp-content
  env_file:
    - ./.env
web:
  image: nginx
  volumes:
    - ./nginx.conf:/etc/nginx/nginx.conf:ro
  links:
    - app
  volumes_from:
    - app
